# version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx-logs:/var/log/nginx
    networks:
      - nginx_network
    restart: always
    depends_on:
      - nodejs

  nodejs:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    image: nodejs
    container_name: nodejs
#    entrypoint:  "dockerize -wait tcp://db:3306 -timeout 40s sh -c \"npm install && node src/index.js\""
    ports:
      - "3000:3000"
#    volumes:
#      - ./nodejs:/usr/src/app
    restart: unless-stopped
    networks:
      - nginx_network
#    depends_on:
#      - db
#
#  db:
#    image: mysql:5.7.16
#    command: --init-file /docker-entrypoint-initdb.d/init.sql
#    container_name: db
#    restart: always
#    tty: true
#    ports:
#      - "3006:3006"
#    volumes:
#      - ./mysql/email_db:/var/lib/mysql
#      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      - MYSQL_DATABASE=emaildb
#      - MYSQL_ROOT_PASSWORD=passwordToChange
#      - MYSQL_USE=root
#    networks:
#      - nginx_network

networks:
  nginx_network:
    driver: bridge
