CREATE DATABASE IF NOT EXISTS emaildb;
USE emaildb;
CREATE TABLE IF NOT EXISTS emailAddresses (
    email VARCHAR(254) UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);
